server:
  port: 9090
#  servlet:
#    context-path: /MQ


# 配置Redis
spring:
  redis:
    host: 172.17.189.164
    port: 31602


example:
  service:
    suffix: 111
    prefix: asd



#url: http://${NODE_IP:127.0.0.1}:${NODE_PORT:8080}/home/index.html
gateway:
  kong:
    apiUrl: ${KONG_API_URL:http://127.0.0.1:8000}
    adminUrl: ${KONG_ADMIN_URL:http://127.0.0.1:8001}
    services:
      - name: baidu
        url: https://www.baidu.com
        routes:
          - name: search
            paths:
              - /search

      - name: bilibili
        url: https://www.bilibili.com
        routes:
          - name: video
            paths:
              - /video
          - name: fun
            paths:
              - /fun


#register:
#  home: http://172.17.189.166:32607
#  consumers:
#    - appName: home
#      appDisplayName: hoime
#      clientId: home





register:
  user:
    username: user1
    custom-id: 156
    tags:
      - tag2
    key: keytoyourheart12
    secret: comeandgetyourlove

