server:
  port: 9090
  servlet:
    context-path: /MQ


# 配置Redis
spring:
  redis:
    host: 172.17.189.164
    port: 31602


example:
  service:
    suffix: 111
    prefix: asd



httpclient:
  retry-times: 11
  base-url: 127.0.0.1
  enabled: false


gateway:
  kong:
    apiUrl: http://127.0.0.1/asset
    adminUrl: ${KONG_ADMIN_URL:http://172.17.189.166:31606}

kong:
  services:
    - name: home-index
      url: http://${NODE_IP:127.0.0.1}:${NODE_PORT:8080}/home/index.html
      routes:
        - name: home-index-route
          paths:
            - /
            - /index.html

register:
  home: http://172.17.189.166:32594
  consumers:
    - appName: h2-test
      appDisplayName: 测试工程
      clientId: h2

    - appName: h2-test1
      appDisplayName: 测试工程1
      clientId: h21
