server:
  port: 9090
#  servlet:
#    context-path: /MQ


# 配置Redis
spring:
  redis:
    host: 172.17.189.164
    port: 31602



gateway:
  kong:
    apiUrl: ${KONG_API_URL:http://127.0.0.1:8000}
    adminUrl: ${KONG_ADMIN_URL:http://127.0.0.1:8001}
    services:
      - name: register
        enableJWT: true
        url: http://127.0.0.1:9090/home
        routes:
          - name: home
            paths:
              - /home


register:
  consumer:
    appName: redispubsub
    client-id: 11baa383-07e3-425c-a60c-34fc7a68016
